
CREATE TABLE IF NOT EXISTS mpa (
        mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar
);
CREATE TABLE IF NOT EXISTS films (
        film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar,
        description varchar(200),
        rate int,
        release_date date,
        mpa_id int REFERENCES mpa (mpa_id),
        duration int,
        likes int
);

CREATE TABLE IF NOT EXISTS genres (
        genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar
);
CREATE TABLE IF NOT EXISTS users (
        user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email varchar,
        login varchar,
        name varchar,
        birthday date
);
CREATE TABLE IF NOT EXISTS friends (
        user_id int REFERENCES users (user_id),
        friend_id int REFERENCES users (user_id),
        PRIMARY KEY (user_id,friend_id)
);
CREATE TABLE IF NOT EXISTS film_genres (
        film_id INTEGER REFERENCES films (film_id),
        genre_id int REFERENCES genres (genre_id),
        PRIMARY KEY (film_id,genre_id)
);
CREATE TABLE IF NOT EXISTS film_liked_users (
        film_id INTEGER REFERENCES films (film_id),
        user_id int REFERENCES users (user_id),
        PRIMARY KEY (film_id,user_id)
);

